# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Trees Land Critters
email: kieran@tlcned.com
# description: >-
#   Trees Land Critters, LLC<br>Nederland, CO
baseurl: ""
url: "https://tlcned.com"
github_username:  tlc-ned

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
